# Generated by Django 4.0 on 2023-11-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='学年・クラス')),
            ],
        ),
        migrations.CreateModel(
            name='CapturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名前')),
                ('num', models.CharField(max_length=10, verbose_name='種類')),
                ('score1', models.IntegerField(verbose_name='英語')),
                ('score2', models.IntegerField(verbose_name='数学')),
                ('score3', models.IntegerField(verbose_name='国語')),
                ('score4', models.IntegerField(verbose_name='理科')),
                ('score5', models.IntegerField(verbose_name='社会')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captureapp.category', verbose_name='学年・クラス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
    ]
